[build]
  command = "npm run build"
  publish = "dist/"
  environment = { NODE_VERSION = "18.3.0" }

[[redirects]]
  from = "/paulingrenade"
  to = "https://www.paulingrenade.com/"
  status = 301
  force = true